version: "3.8"
services:
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./user-service/.env

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ./order-service/.env

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./api-gateway/.env